### ISSUE TITLE
Body Class returns nothing

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-layout_module-base-2019#2]
the component returns nothing at all. Hugo 0.54

https://github.com/theNewDynamic/hugo-layout_module-base-2019/blob/master/layouts/partials/_components/body-class.html

**Comment by budparr** [comment]
p.s. @regisphilibert No rush on this,  I couldn't figure this out, so  I just added `{{ .Kind }} {{ .Type }} {{ .Layout }}` to the baseof on the site I'm working on.

**Comment by regisphilibert** [comment]
https://github.com/theNewDynamic/hugo-layout_module-base-2019/commit/dedf023df607f37899fefcfd2c4ad7ea16d82691
